package com.ht.jcbk.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-17T16:04:34.140+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://webservice.jcbk.ht.com", name = "InAccess")
@XmlSeeAlso({ObjectFactory.class})
public interface InAccess {

    @WebMethod
    @RequestWrapper(localName = "executes", targetNamespace = "http://webservice.jcbk.ht.com", className = "com.ht.jcbk.webservice.Executes")
    @ResponseWrapper(localName = "executesResponse", targetNamespace = "http://webservice.jcbk.ht.com", className = "com.ht.jcbk.webservice.ExecutesResponse")
    @WebResult(name = "executesReturn", targetNamespace = "http://webservice.jcbk.ht.com")
    public java.lang.String executes(
        @WebParam(name = "SystemType", targetNamespace = "http://webservice.jcbk.ht.com")
        java.lang.String systemType,
        @WebParam(name = "BusinessType", targetNamespace = "http://webservice.jcbk.ht.com")
        java.lang.String businessType,
        @WebParam(name = "sn", targetNamespace = "http://webservice.jcbk.ht.com")
        java.lang.String sn,
        @WebParam(name = "xml", targetNamespace = "http://webservice.jcbk.ht.com")
        java.lang.String xml
    );
}
