package com.ht.jcbk.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-17T16:04:34.171+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "InAccessService", 
                  wsdlLocation = "http://10.44.13.34:9080/dc/services/InAccess?wsdl",
                  targetNamespace = "http://webservice.jcbk.ht.com") 
public class InAccessService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.jcbk.ht.com", "InAccessService");
    public final static QName InAccess = new QName("http://webservice.jcbk.ht.com", "InAccess");
    static {
        URL url = null;
        try {
            url = new URL("http://10.44.13.34:9080/dc/services/InAccess?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InAccessService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.44.13.34:9080/dc/services/InAccess?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InAccessService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InAccessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InAccessService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InAccessService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InAccessService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InAccessService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns InAccess
     */
    @WebEndpoint(name = "InAccess")
    public InAccess getInAccess() {
        return super.getPort(InAccess, InAccess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InAccess
     */
    @WebEndpoint(name = "InAccess")
    public InAccess getInAccess(WebServiceFeature... features) {
        return super.getPort(InAccess, InAccess.class, features);
    }

}
