package com.sunshine.monitor.system.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-05T17:27:24.859+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://server.ws.system.monitor.sunshine.com/", name = "QueryVehPassrecService")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryVehPassrecService {

    @WebMethod
    @RequestWrapper(localName = "queryVehPassrec", targetNamespace = "http://server.ws.system.monitor.sunshine.com/", className = "com.sunshine.monitor.system.ws.server.QueryVehPassrec")
    @ResponseWrapper(localName = "queryVehPassrecResponse", targetNamespace = "http://server.ws.system.monitor.sunshine.com/", className = "com.sunshine.monitor.system.ws.server.QueryVehPassrecResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.sunshine.monitor.system.ws.server.VehPassrec> queryVehPassrec(
        @WebParam(name = "queryConditions", targetNamespace = "")
        com.sunshine.monitor.system.ws.server.QueryVehPassrecEntity queryConditions
    );
}
