package com.sunshine.monitor.system.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-05T17:27:24.875+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "QueryVehPassrecService", 
                  wsdlLocation = "http://10.43.64.181:9080/jcbk/service/QueryVehPassrecServer?wsdl",
                  targetNamespace = "http://server.ws.system.monitor.sunshine.com/") 
public class QueryVehPassrecService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.ws.system.monitor.sunshine.com/", "QueryVehPassrecService");
    public final static QName QueryVehPassrecServiceImplPort = new QName("http://server.ws.system.monitor.sunshine.com/", "QueryVehPassrecServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.43.64.181:9080/jcbk/service/QueryVehPassrecServer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryVehPassrecService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.43.64.181:9080/jcbk/service/QueryVehPassrecServer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryVehPassrecService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryVehPassrecService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryVehPassrecService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QueryVehPassrecService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryVehPassrecService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryVehPassrecService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QueryVehPassrecService
     */
    @WebEndpoint(name = "QueryVehPassrecServiceImplPort")
    public QueryVehPassrecService getQueryVehPassrecServiceImplPort() {
        return super.getPort(QueryVehPassrecServiceImplPort, QueryVehPassrecService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryVehPassrecService
     */
    @WebEndpoint(name = "QueryVehPassrecServiceImplPort")
    public QueryVehPassrecService getQueryVehPassrecServiceImplPort(WebServiceFeature... features) {
        return super.getPort(QueryVehPassrecServiceImplPort, QueryVehPassrecService.class, features);
    }

}
