package com.dyst.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Jul 22 21:14:08 CST 2016
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://ws.dyst.com", name = "InterfaceServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface InterfaceServicePortType {

    @WebMethod
    @RequestWrapper(localName = "executes", targetNamespace = "http://ws.dyst.com", className = "com.dyst.ws.Executes")
    @ResponseWrapper(localName = "executesResponse", targetNamespace = "http://ws.dyst.com", className = "com.dyst.ws.ExecutesResponse")
    @WebResult(name = "out", targetNamespace = "http://ws.dyst.com")
    public java.lang.String executes(
        @WebParam(name = "in0", targetNamespace = "http://ws.dyst.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.dyst.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.dyst.com")
        java.lang.String in2
    );
}
