
/*
 * 
 */

package com.dyst.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Jul 22 21:14:08 CST 2016
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "InterfaceService", 
                  wsdlLocation = "http://10.42.127.81:8989/interface/services/interfaceService?wsdl",
                  targetNamespace = "http://ws.dyst.com") 
public class InterfaceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.dyst.com", "InterfaceService");
    public final static QName InterfaceServiceHttpPort = new QName("http://ws.dyst.com", "InterfaceServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.42.127.81:8989/interface/services/interfaceService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.42.127.81:8989/interface/services/interfaceService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns InterfaceServicePortType
     */
    @WebEndpoint(name = "InterfaceServiceHttpPort")
    public InterfaceServicePortType getInterfaceServiceHttpPort() {
        return super.getPort(InterfaceServiceHttpPort, InterfaceServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceServicePortType
     */
    @WebEndpoint(name = "InterfaceServiceHttpPort")
    public InterfaceServicePortType getInterfaceServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(InterfaceServiceHttpPort, InterfaceServicePortType.class, features);
    }

}
