package com.dyst.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Jul 22 21:32:39 CST 2016
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://webservice.dyst.com", name = "IInAccessServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IInAccessServicePortType {

    @WebMethod
    @RequestWrapper(localName = "executes", targetNamespace = "http://webservice.dyst.com", className = "com.dyst.webservice.Executes")
    @ResponseWrapper(localName = "executesResponse", targetNamespace = "http://webservice.dyst.com", className = "com.dyst.webservice.ExecutesResponse")
    @WebResult(name = "out", targetNamespace = "http://webservice.dyst.com")
    public java.lang.String executes(
        @WebParam(name = "in0", targetNamespace = "http://webservice.dyst.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.dyst.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.dyst.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.dyst.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.dyst.com")
        java.lang.String in4
    );
}
