
/*
 * 
 */

package com.dyst.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Jul 22 21:32:39 CST 2016
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "IInAccessService", 
                  wsdlLocation = "http://10.42.31.224:8080/dyst/services/InAccess?wsdl",
                  targetNamespace = "http://webservice.dyst.com") 
public class IInAccessService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.dyst.com", "IInAccessService");
    public final static QName IInAccessServiceHttpPort = new QName("http://webservice.dyst.com", "IInAccessServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.42.31.224:8080/dyst/services/InAccess?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.42.31.224:8080/dyst/services/InAccess?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public IInAccessService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IInAccessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IInAccessService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IInAccessServicePortType
     */
    @WebEndpoint(name = "IInAccessServiceHttpPort")
    public IInAccessServicePortType getIInAccessServiceHttpPort() {
        return super.getPort(IInAccessServiceHttpPort, IInAccessServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IInAccessServicePortType
     */
    @WebEndpoint(name = "IInAccessServiceHttpPort")
    public IInAccessServicePortType getIInAccessServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(IInAccessServiceHttpPort, IInAccessServicePortType.class, features);
    }

}
