package com.sunshine.monitor.system.ws.businessservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-28T10:51:48.796+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "BusinessAccessService", 
                  wsdlLocation = "http://10.44.98.202:8080/jcbk/service/OutAccess?wsdl",
                  targetNamespace = "http://businessService.ws.system.monitor.sunshine.com/") 
public class BusinessAccessService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://businessService.ws.system.monitor.sunshine.com/", "BusinessAccessService");
    public final static QName OutAccess = new QName("http://businessService.ws.system.monitor.sunshine.com/", "OutAccess");
    static {
        URL url = null;
        try {
            url = new URL("http://10.44.98.202:8080/jcbk/service/OutAccess?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BusinessAccessService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.44.98.202:8080/jcbk/service/OutAccess?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BusinessAccessService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BusinessAccessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusinessAccessService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BusinessAccessService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BusinessAccessService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BusinessAccessService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BusinessService
     */
    @WebEndpoint(name = "OutAccess")
    public BusinessService getOutAccess() {
        return super.getPort(OutAccess, BusinessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessService
     */
    @WebEndpoint(name = "OutAccess")
    public BusinessService getOutAccess(WebServiceFeature... features) {
        return super.getPort(OutAccess, BusinessService.class, features);
    }

}
