package com.sunshine.monitor.system.ws.businessservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-28T10:51:48.703+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://businessService.ws.system.monitor.sunshine.com/", name = "BusinessService")
@XmlSeeAlso({ObjectFactory.class})
public interface BusinessService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "executes", targetNamespace = "http://businessService.ws.system.monitor.sunshine.com/", className = "com.sunshine.monitor.system.ws.businessservice.Executes")
    @WebMethod
    @ResponseWrapper(localName = "executesResponse", targetNamespace = "http://businessService.ws.system.monitor.sunshine.com/", className = "com.sunshine.monitor.system.ws.businessservice.ExecutesResponse")
    public java.lang.String executes(
        @WebParam(name = "systemType", targetNamespace = "")
        java.lang.String systemType,
        @WebParam(name = "businessType", targetNamespace = "")
        java.lang.String businessType,
        @WebParam(name = "sn", targetNamespace = "")
        java.lang.String sn,
        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "execute", targetNamespace = "http://businessService.ws.system.monitor.sunshine.com/", className = "com.sunshine.monitor.system.ws.businessservice.Execute")
    @WebMethod
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://businessService.ws.system.monitor.sunshine.com/", className = "com.sunshine.monitor.system.ws.businessservice.ExecuteResponse")
    public java.lang.String execute(
        @WebParam(name = "systemType", targetNamespace = "")
        java.lang.String systemType,
        @WebParam(name = "businessType", targetNamespace = "")
        java.lang.String businessType,
        @WebParam(name = "sn", targetNamespace = "")
        java.lang.String sn,
        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "feedBack", targetNamespace = "http://businessService.ws.system.monitor.sunshine.com/", className = "com.sunshine.monitor.system.ws.businessservice.FeedBack")
    @WebMethod
    @ResponseWrapper(localName = "feedBackResponse", targetNamespace = "http://businessService.ws.system.monitor.sunshine.com/", className = "com.sunshine.monitor.system.ws.businessservice.FeedBackResponse")
    public java.lang.String feedBack(
        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml
    );
}
