package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Jul 22 20:05:58 CST 2016
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebMethod(operationName = "PicCall2", action = "http://tempuri.org/PicCall2")
    @RequestWrapper(localName = "PicCall2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PicCall2")
    @ResponseWrapper(localName = "PicCall2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PicCall2Response")
    @WebResult(name = "PicCall2Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String picCall2(
        @WebParam(name = "str_tpid", targetNamespace = "http://tempuri.org/")
        java.lang.String strTpid
    );

    @WebMethod(operationName = "PicCall1", action = "http://tempuri.org/PicCall1")
    @RequestWrapper(localName = "PicCall1", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PicCall1")
    @ResponseWrapper(localName = "PicCall1Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PicCall1Response")
    @WebResult(name = "PicCall1Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String picCall1(
        @WebParam(name = "str_tpid", targetNamespace = "http://tempuri.org/")
        java.lang.String strTpid
    );

    @WebMethod(operationName = "MyDoorTest", action = "http://tempuri.org/MyDoorTest")
    @RequestWrapper(localName = "MyDoorTest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyDoorTest")
    @ResponseWrapper(localName = "MyDoorTestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyDoorTestResponse")
    @WebResult(name = "MyDoorTestResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String myDoorTest(
        @WebParam(name = "strYzid", targetNamespace = "http://tempuri.org/")
        java.lang.String strYzid,
        @WebParam(name = "strHphm", targetNamespace = "http://tempuri.org/")
        java.lang.String strHphm,
        @WebParam(name = "strHpzl", targetNamespace = "http://tempuri.org/")
        java.lang.String strHpzl
    );

    @WebMethod(action = "http://tempuri.org/jsyxxcx")
    @RequestWrapper(localName = "jsyxxcx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Jsyxxcx")
    @ResponseWrapper(localName = "jsyxxcxResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JsyxxcxResponse")
    @WebResult(name = "jsyxxcxResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String jsyxxcx(
        @WebParam(name = "str_zjlx", targetNamespace = "http://tempuri.org/")
        java.lang.String strZjlx,
        @WebParam(name = "str_zjhm", targetNamespace = "http://tempuri.org/")
        java.lang.String strZjhm
    );

    @WebMethod(operationName = "MyDoor", action = "http://tempuri.org/MyDoor")
    @RequestWrapper(localName = "MyDoor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyDoor")
    @ResponseWrapper(localName = "MyDoorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyDoorResponse")
    public void myDoor(
        @WebParam(name = "strYzid", targetNamespace = "http://tempuri.org/")
        java.lang.String strYzid,
        @WebParam(name = "strHphm", targetNamespace = "http://tempuri.org/")
        java.lang.String strHphm,
        @WebParam(name = "strHpzl", targetNamespace = "http://tempuri.org/")
        java.lang.String strHpzl,
        @WebParam(mode = WebParam.Mode.OUT, name = "MyDoorResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> myDoorResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strFactBrand", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strFactBrand,
        @WebParam(mode = WebParam.Mode.OUT, name = "strModel", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strModel,
        @WebParam(mode = WebParam.Mode.OUT, name = "strVehicleTypeDetail", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strVehicleTypeDetail,
        @WebParam(mode = WebParam.Mode.OUT, name = "strColorDetail", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strColorDetail,
        @WebParam(mode = WebParam.Mode.OUT, name = "strBodyNo", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strBodyNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "strEngineNo", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strEngineNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "strOwnerName", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strOwnerName,
        @WebParam(mode = WebParam.Mode.OUT, name = "strCertNo", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strCertNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "strAddr", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strAddr,
        @WebParam(mode = WebParam.Mode.OUT, name = "strTel", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strTel,
        @WebParam(mode = WebParam.Mode.OUT, name = "strZip", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strZip,
        @WebParam(mode = WebParam.Mode.OUT, name = "strCity", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strCity,
        @WebParam(mode = WebParam.Mode.OUT, name = "strFirstRegTime", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strFirstRegTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "strLatestChkTime", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strLatestChkTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "strChkValidTime", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strChkValidTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "strIssueCertTime", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strIssueCertTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "strVehicleStatDetail", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strVehicleStatDetail,
        @WebParam(mode = WebParam.Mode.OUT, name = "strDiscardTime", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strDiscardTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "strSteerPosDetail", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strSteerPosDetail,
        @WebParam(mode = WebParam.Mode.OUT, name = "strRet", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strRet
    );

    @WebMethod(operationName = "HC", action = "http://tempuri.org/HC")
    @RequestWrapper(localName = "HC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HC")
    @ResponseWrapper(localName = "HCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HCResponse")
    @WebResult(name = "HCResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String hc(
        @WebParam(name = "strYzid", targetNamespace = "http://tempuri.org/")
        java.lang.String strYzid,
        @WebParam(name = "strHphm", targetNamespace = "http://tempuri.org/")
        java.lang.String strHphm,
        @WebParam(name = "strHpzl", targetNamespace = "http://tempuri.org/")
        java.lang.String strHpzl
    );

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String helloWorld();
}
